---
- name: Install python-openssl system package
  apt:
    name: python-openssl
    state: latest
    update_cache: yes
  become: true

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ private_key_path|dirname }}"
    - "{{ crt_directory }}"
    - "{{ csr_directory }}"
  become: true

- name: Create account key and private key
  openssl_privatekey:
    path: "{{ item }}"
  register: create_keys
  with_items:
    - "{{ account_key_path }}"
    - "{{ private_key_path }}"
  become: true

- name: Delete CSRs if keys have changed
  file:
    path: "{{ csr_directory }}"
    state: absent
  when: create_keys|changed
  become: true

- name: Create CSRs
  openssl_csr:
    path: "{{ csr_directory }}/{{ item.domain }}.csr"
    privatekey_path: "{{ private_key_path }}"
    countryName: CA
    commonName: "{{ item.domain }}"
  register: create_csrs
  with_items: "{{ websites }}"
  become: true

- name: Letsencrypt challenge
  letsencrypt:
    account_email: "{{ account_email }}"
    account_key: "{{ account_key_path }}"
    acme_directory: "{{ acme_directory }}"
    csr: "{{ csr_directory }}/{{ item.domain }}.csr"
    dest: "{{ crt_directory }}/{{ item.domain }}.crt"
  register: letsencrypt_challenge
  when: create_csrs|changed
  with_items: "{{ websites }}"
  become: true

- name: Create challenge resource directories
  file:
    path: "{{ web_root_directory }}/{{ item.item.domain }}/{{ item['challenge_data'][ item.item.domain ]['http-01']['resource']|dirname }}"
    state: directory
  when: item.changed
  with_items: "{{ letsencrypt_challenge.results }}"
  become: true

- name: Copy challenge resources
  copy:
    dest: "{{ web_root_directory }}/{{ item.item.domain }}/{{ item['challenge_data'][ item.item.domain ]['http-01']['resource'] }}"
    content: "{{ item['challenge_data'][ item.item.domain ]['http-01']['resource_value'] }}"
  when: item.changed
  with_items: "{{ letsencrypt_challenge.results }}"
  become: true

- name: Issue certificates
  letsencrypt:
    account_email: "{{ account_email }}"
    account_key: "{{ account_key_path }}"
    acme_directory: "{{ acme_directory }}"
    csr: "{{ csr_directory }}/{{ item.item.domain }}.csr"
    dest: "{{ crt_directory }}/{{ item.item.domain }}.crt"
    data: "{{ item }}"
  register: issue_certificates
  when: item.changed
  with_items: "{{ letsencrypt_challenge.results }}"
  become: true
