---
- name: restart nginx
  systemd:
    name: nginx
    daemon_reload: yes
    state: restarted
  become: true

- name: restart php-fpm
  systemd:
    name: php7.0-fpm
    daemon_reload: yes
    state: restarted
  become: true
